apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    app: {{ .Values.ingress.name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: {{.Values.ingress.certName}}
    kubernetes.io/ingress.global-static-ip-name: {{.Values.ingress.staticIpName}}
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: {{.Values.service.name}}
          servicePort: 80
