version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.7.1

commands:
  gke-auth:
    steps:
      - run:
          name: Authenticate on gcloud
          command: |
            echo ${GCLOUD_SERVICE_KEY} > gcloud-service-key.json
            gcloud auth activate-service-account --key-file=gcloud-service-key.json
            gcloud config set project ${GOOGLE_PROJECT_ID}
            gcloud container clusters get-credentials testnet-cluster --region us-central1-a --project ${GOOGLE_PROJECT_ID}

jobs:          
  build_lnpage:
    working_directory: ~/
    machine: true
    steps:
      - checkout:
          path: ~/
      - gcp-gcr/build-image:
          image: lnpage
          tag: $CIRCLE_SHA1
      - gcp-gcr/gcr-auth
      - gcp-gcr/push-image:
          image: lnpage
          tag: $CIRCLE_SHA1

workflows:
  build_lnpage:
    jobs:
      - build_lnpage
