version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0

commands:
  gke-auth:
    steps:
    - run:
        name: Authenticate on gcloud
        command: |
          echo ${GCLOUD_SERVICE_KEY} > gcloud-service-key.json
          gcloud auth activate-service-account --key-file=gcloud-service-key.json
          gcloud config set project ${GOOGLE_PROJECT_ID}
          gcloud container clusters get-credentials testnet-cluster --region us-central1-a --project ${GOOGLE_PROJECT_ID}

jobs:          
  build_lnpage:
    machine: true
    steps:
      - checkout
      - gcp-gcr/build-image:
          image: lnpage
      - gcp-gcr/gcr-auth
      - gcp-gcr/push-image:
          image: lnpage
      - run:
          name: Tag the approved image
          command: |
            IMAGE_ROOT=gcr.io/${GOOGLE_PROJECT_ID}/lnpage
            gcloud container images add-tag --quiet "${IMAGE_ROOT}:approved" "${IMAGE_ROOT}:${CIRCLE_BUILD_NUM}"

workflows:
  build_lnpage:
    jobs:
      - build_lnpage
