version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0

commands:
  gke-auth:
    steps:
    - run:
        name: Authenticate on gcloud
        command: |
          echo ${GCLOUD_SERVICE_KEY} > gcloud-service-key.json
          gcloud auth activate-service-account --key-file=gcloud-service-key.json
          gcloud config set project ${GOOGLE_PROJECT_ID}
          gcloud container clusters get-credentials testnet-cluster --region us-central1-a --project ${GOOGLE_PROJECT_ID}

jobs:          
  build_lnpage:
    machine: true
    steps:
      - checkout
      - gcp-gcr/build-image:
          image: lnpage
          tag: approved
      - gcp-gcr/gcr-auth
      - run:
          name: Compute tag
          command: |
            export TAG=$(gcloud container images list-tags gcr.io/galoyapp/lnpage --filter="tags[]=approved" \
            | awk 'FNR == 2 {print $2}'| awk -F, '{print $1}')
            echo tag "$TAG"
            TAG=$(($TAG+1))
            echo "export TAG=$TAG" >> $BASH_ENV
      - gcp-gcr/push-image:
          image: lnpage
          tag: approved
      - run:
          name: Tag the approved image
          command: |
            IMAGE_ROOT=gcr.io/${GOOGLE_PROJECT_ID}/lnpage
            gcloud container images add-tag --quiet "${IMAGE_ROOT}:approved" "${IMAGE_ROOT}:${TAG}"

workflows:
  build_lnpage:
    jobs:
      - build_lnpage
