name: Build and Push to GCR

on:
  push:
    branches:
      - main

jobs:
   build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: galoy-app
          image_name: lnpage
