name: "Dealer Unit test"

on:
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    name: Dealer Unit test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: yarn install
    - name: Run unit tests
      run: make dealer-unit-in-ci
