name: "Dealer Integration test"

on:
  pull_request:
    branches: [ main ]

jobs:
  integration:
    name: Dealer Integration test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: yarn install
    - name: Run integration tests
      run: docker-compose up -d && sleep 10 && make dealer-integration-in-ci

