name: Add tag to docker image

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gcr.io/galoyapp/lnpage:latest,gcr.io/galoyapp/lnpage:${{ github.sha }}
  build:
    needs: build-and-push-to-gcr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCLOUD_SERVICE_KEY }}
    - name: Tag latest image
      run: |
        docker pull gcr.io/galoyapp/lnpage:latest
        docker tag gcr.io/galoyapp/lnpage:latest gcr.io/galoyapp/lnpage:$TAG
        docker push gcr.io/galoyapp/lnpage:$TAG
